apiVersion: v1
kind: Pod
metadata: 
  name: result-app-pod
  labels:
    name: result-app-pod
    app: demo-voting-app
sepc:
  containers:
    - image: kodecloud/examplevotingapp_result:v1
      name: result-app 
      ports: 
        containerPorts: 80