apiVersion: v1
kind: Pod
metadata: 
  name: worker-pod
  labels:
    name: worker-pod
    app: demo-voting-app
sepc:
  containers:
    - image: workerapp
      name: postgrkodecloud/examplevotingapp_worker:v1