apiVersion: v1
kind: Deployment
metadata:
  name:  result-app-deploy
  labels:
    name: result-app-deploy
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: result-app-pod
      app: demo-voting-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata: 
      name: result-app-pod
      labels:
        name: result-app-pod
        app: demo-voting-app
    sepc:
      containers:
        - image: kodecloud/examplevotingapp_result:v1
          name: result-app 
          ports: 
            containerPorts: 80