apiVersion: v1
kind: Deployment
metadata:
  name:  worker-app-deploy
  labels:
    name:  worker-app-deploy
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: worker-pod
      app: demo-voting-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata: 
      name: worker-pod
      labels:
        name: worker-pod
        app: demo-voting-app
    spec:
      containers:
        - image: workerapp
          name: postgrkodecloud/examplevotingapp_worker:v1